plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
    id 'com.google.devtools.ksp'
//    id 'maven-publish'
    // vanniktech-publish-plugin
    id "com.vanniktech.maven.publish" version "0.34.0"
}

android {
    namespace 'com.swallow.fly'

    compileSdkVersion 35
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        minSdk 24
        targetSdk 35

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }

//    publishing {
//        singleVariant("release") {
//            withSourcesJar()
//            withJavadocJar()
//        }
//    }
    lint {
        abortOnError false
        checkReleaseBuilds true
    }
}
kotlin {
    // Kotlin 工具链方式，自动选择并使用 JDK 17
    jvmToolchain(17)
}
dependencies {
    api fileTree(dir: "libs", include: ["*.jar"])
    // Test
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    //===============================AndroidX基础库================================================//
    api 'com.google.android.material:material:1.13.0'
    api 'androidx.core:core-ktx:1.16.0'
    api 'androidx.appcompat:appcompat:1.7.1'
    api 'androidx.recyclerview:recyclerview:1.4.0'
    api 'androidx.constraintlayout:constraintlayout:2.2.1'
    api 'androidx.vectordrawable:vectordrawable:1.2.0'
    api "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

    api "androidx.fragment:fragment-ktx:1.8.9"
    api "androidx.hilt:hilt-navigation-fragment:1.3.0"

    api 'androidx.legacy:legacy-support-v4:1.0.0'
    //====================================JetPack=================================================//
    // Hilt
    api "com.google.dagger:hilt-android:2.57.2"
    kapt "com.google.dagger:hilt-compiler:2.57.2"

    // Lifecycle
    def lifecycle_version = "2.9.4"
    // LiveData
    api "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    // ViewModel
    api "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    // Lifecycles only (without ViewModel or LiveData)
    api "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    api "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    // Saved state module for ViewModel
    api "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"

    // Paging
    api "androidx.paging:paging-runtime-ktx:3.3.6"
    // Navigation
    def navigation_version = "2.9.5"
    api "androidx.navigation:navigation-fragment-ktx:$navigation_version"
    api "androidx.navigation:navigation-ui-ktx:$navigation_version"

    // ViewPager2
    api "androidx.viewpager2:viewpager2:1.1.0"
    // 协程
    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    //================================ 事件总线 ===================================================//
    api 'org.greenrobot:eventbus:3.3.1'
    //================================= Room数据库 ================================================//
    def room_version = "2.8.3"
    api "androidx.room:room-runtime:$room_version"
    ksp "androidx.room:room-compiler:$room_version"
    // 添加数据库测试支持
    api 'android.arch.persistence.room:testing:1.1.1'
    //================================= Glide图片加载 =============================================//
    def glide_version = "5.0.5"
    api "com.github.bumptech.glide:glide:$glide_version"
    api "com.github.bumptech.glide:okhttp3-integration:$glide_version"
    //================================= Retrofit网络框架 ==========================================//
    def retrofit_version = "3.0.0"
    api "com.squareup.retrofit2:retrofit:$retrofit_version"
    api "com.squareup.retrofit2:converter-gson:$retrofit_version"
    // okHttp
//    api 'com.squareup.okhttp3:okhttp:4.3.0'
//    api 'com.squareup.okhttp3:logging-interceptor:4.3.0'
    // 动态切换域名支持
    api 'me.jessyan:retrofit-url-manager:1.4.0'
    // multi-dex
    api 'androidx.multidex:multidex:2.0.1'
    //================================= ARouter =============================================//
    api 'com.alibaba:arouter-api:1.5.2'
    //================================= 工具类库 =============================================//
    // Timber
    api 'com.jakewharton.timber:timber:5.0.1'
    // immersionbar support android 15、16
    api 'com.github.OCNYang.ImmersionBar:immersionbar:3.4.0'
    //权限
    api 'pub.devrel:easypermissions:3.0.0'
    // 工具类库
    api("com.blankj:utilcodex:1.31.1") {
        exclude group: "org.jetbrains.kotlin", module: "kotlin-android-extensions-runtime"
    }
    // MMKV
    api 'com.tencent:mmkv-static:2.2.4'
}

//publishing {
//    publications {
//        release(MavenPublication) {
//            groupId = 'com.github.hpuhsp'
//            artifactId = 'gyps'
//            version = '1.5.0-snapshot'
//
//            afterEvaluate {
//                from components.release
//            }
//        }
//    }
//}


//=============================构建操作=============================================================>
// 上传Bintray(不再使用)
//apply from: '../buildScripts/gradle/bintray.gradle'
// 上传Nexus私服
//apply from: '../buildScripts/gradle/nexus_upload.gradle'

// 上传Maven 中央仓库
//ext {
//    PUBLISH_GROUP_ID = 'io.github.hpuhsp'
//    PUBLISH_ARTIFACT_ID = 'gyps'
//    PUBLISH_VERSION = '1.0.0'
//}
//apply from: "${rootProject.projectDir}/buildScripts/gradle/publish-mavencentral.gradle"
//apply from: "${rootProject.projectDir}/buildScripts/gradle/upload_archives.gradle"